## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Ientile Avocat"
# theme = "hugo-story"
baseURL = "https://www.ientile-avocat.fr/"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "A (modular, highly tweakable) responsive one-page theme for Hugo"
  logo = "images/LGoV2e74RQK1ReXkOh6yKg.jpeg"
  favicon = true

[Params.social]
  linkedin = "https://www.linkedin.com/in/evanna-ientile-a57b1b97/"

# Pour que le theme marche
[module]
  [[module.imports]]
    path = "github.com/caressofsteel/hugo-story"

###########
# Barriere pour pas que le theme s'en aille vu qu'il marche
